HallofFame/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from halls import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),

    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    # Halls
    path('halloffame/create', views.CreateHall.as_view(), name='create_hall'),
    path('halloffame/<int:pk>', views.DetailHall.as_view(), name='detail_hall'),
    path('halloffame/<int:pk>/update',
         views.UpdateHall.as_view(), name='update_hall'),
    path('halloffame/<int:pk>/delete',
         views.DeleteHall.as_view(), name='delete_hall'),

    # Videos
    path('halloffame/<int:pk>/addvideo',
         views.add_video, name='add_video'),
    path('video/search',
         views.video_search, name='video_search'),
    path('videos/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video'),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django.contrib.auth.models import User


class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(
        User, on_delete=models.CASCADE)


class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(
        Hall, on_delete=models.CASCADE, null=True)

halls/forms.py
from .models import Video
from django import forms


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url': 'YouTube URL'}


class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='search for videos:')

halls/views.py
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from .models import Hall, Video
from .forms import VideoForm, SearchForm
from django.forms import formset_factory
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import Http404, JsonResponse
import urllib
import requests
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.

YOUTUBE_API_KEY = 'AIzaSyAMrY6sp7LbgDi5lIgy74T-e5SLevSG_PI'


def home(request):
    recent_halls = Hall.objects.all().order_by('-id')[:3]
    popular_halls = [Hall.objects.get(pk=1)]
    return render(request, 'halls/home.html', {'recent_halls': recent_halls, 'popular_halls': popular_halls})


@login_required
def dashboard(request):
    halls = Hall.objects.filter(user=request.user)
    return render(request, 'halls/dashboard.html', {'halls': halls})


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'
    # we can make the user login directly after signup

    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get(
            'username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class CreateHall(LoginRequiredMixin, generic.CreateView):
    model = Hall
    fields = ['title']
    template_name = 'halls/create_hall.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreateHall, self).form_valid(form)
        return redirect('dashboard')


class DetailHall(generic.DetailView):
    model = Hall
    template_name = 'halls/detail_hall.html'


class UpdateHall(LoginRequiredMixin, generic.UpdateView):
    model = Hall
    template_name = 'halls/update_hall.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(UpdateHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall


class DeleteHall(LoginRequiredMixin, generic.DeleteView):
    model = Hall
    template_name = 'halls/delete_hall.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall
# use cbv if ur using a particular base of  a model which is not too complicated
# like for an object if we want to create a view to create,update delete then use cbv
# for The model Video it might get a bit messy using only cbvs then we use function based views as well


@login_required
def add_video(request, pk):
    # VideoFormset = formset_factory(VideoForm, extra=5)
    # form = VideoFormset()
    form = VideoForm()
    search_form = SearchForm()
    hall = Hall.objects.get(pk=pk)
    if not hall.user == request.user:
        raise Http404
    if request.method == "POST":
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(
                    f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id[0] }&key={YOUTUBE_API_KEY}')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.hall = hall
                video.save()
                return redirect('detail_hall', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Needs to be a YouTube URL')
    return render(request, 'halls/add_video.html', {'form': form, 'search_form': search_form, 'hall': hall})


@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    print(search_form.errors)
    if search_form.is_valid():
        enc_search_term = urllib.parse.quote(
            search_form.cleaned_data['search_term'])
        response = requests.get(
            f'https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={ enc_search_term }&key={YOUTUBE_API_KEY }')
        return JsonResponse(response.json())
    return JsonResponse({'error': 'Not able to validate form'})


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'halls/del_vid.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        return video

halls/templates/halls/add_video.html
{% extends "halls/base.html" %} {%block content%}
<div class="container">
  <h2>Add video to {{hall.title}}</h2>
  {% load crispy_forms_tags %}
  <form method="POST" id="sub">
    {% csrf_token %} {{form|crispy}}
    <button type="submit" class="btn btn-primary">Upload</button>
  </form>
  <br />
  <h2>Or</h2>
  <form>{{search_form|crispy}}</form>
  <div id="search_results"></div>
  <script>
    var delayTimer;
    $("#id_search_term").keyup(function () {
      clearTimeout(delayTimer);
      $("#search_results").text("Loading...");
      delayTimer = setTimeout(function () {
        var text = $("#id_search_term").val();
        $.ajax({
          url: "/video/search",
          data: {
            search_term: text,
          },
          dataType: "json",
          success: function (data) {
            var result = "";
            $("#search_results").text("");
            result += '<div class="row">';
            data["items"].forEach(function (video) {
              result +=
                '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
              result +=
                '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' +
                video["id"]["videoId"] +
                '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
              result +=
                '<div class="card-body"><p class="card-text">' +
                video["snippet"]["title"] +
                "</p>";
              result +=
                '<a href="#" class="btn btn-primary" onclick="addVideo(\'' +
                video["id"]["videoId"] +
                "')\">Add</a></div></div></div>";
            });
            result += "</div>";
            $("#search_results").append(result);
          },
        });
      }, 2000);
    });
    function addVideo(video_id) {
      $("#id_url").val("https://www.youtube.com/watch?v=" + video_id);
      $("#sub").submit();
    }
  </script>
</div>
{% endblock %}

<!-- <form method="post">
  {% csrf_token %} {%load widget_tweaks%} {%for field in form%}
  <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
    {{field.errors}} {{field.label_tag}} {% render_field field
    class="form-control" %}
  </div>
  {%endfor%}
  {% comment %} {{formset.management_form}} {%for aform in form%}
  {% endcomment %} {% comment %} {% for field in form %}
  <p>
    {{field.errors}} {% comment %} for errors {% endcomment %} {% comment %}
    {{field.label_tag}} {{field}}
  </p>
  {%endfor%} {% endcomment %}
  <button type="submit" class="btn btn-primary">Create</button>
</form> -->

halls/templates/halls/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hall Of Fame</title>
    {% comment %}
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
    {% endcomment %}
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'custom.css' %}" />
    <link
      rel="shortcut icon"
      type="image/png"
      href="{% static 'favicon.ico' %}"
    />
  </head>
  <body>
    <div
      class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm"
    >
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="{% url 'home'%}" class="text-dark">Hall Of Fame Videos</a>
      </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
        {% endif %}
      </nav>
      {% if user.is_authenticated == False %}
      <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign Up</a>
      {% endif %}
    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    {% block content %} {% endblock %}
  </body>
</html>

halls/templates/halls/create_hall.html
{% extends "halls/base.html" %} {%block content%}
<div class="container">
  <h2>Create a hall of fame</h2>
  {% load crispy_forms_tags %}
  <form method="post">
    {{form|crispy}} {% csrf_token %}
    <button type="submit" class="btn btn-primary">Create</button>
  </form>
</div>
{% endblock %}

halls/templates/halls/dashboard.html
{% extends "halls/base.html" %} {% block content %}
<div class="container">
  <div class="text-center">
    <h1>{{user.username}}'s Hall Of Fame</h1>
    <a href="{% url 'create_hall' %}" class="btn btn-primary"
      >Create new hall of fame</a
    >
  </div>
  {% for hall in halls %}

  <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
  <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Delete</a>
  <a href="{% url 'update_hall' hall.id %}" class="btn btn-primary">Edit</a>
  <a href="{% url 'add_video' hall.id %}" class="btn btn-primary">Add Video</a>

  <div class="row">
    {% for vid in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe
          width="100%"
          height="225"
          src="https://www.youtube.com/embed/'{{vid.youtube_Id }}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
        <div class="card-body"><p class="card-text">{{vid.title}}</p></div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</div>
{% endblock %}

halls/templates/halls/del_vid.html
{% extends "halls/base.html" %} {%block content%}
<div class="container">
  <h2>Are u sure you want to delete this video?</h2>
  <form method="post">
    {{form.as_p}} {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
  <br />
  <div class="row">
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe
          width="100%"
          height="225"
          src="https://www.youtube.com/embed/'{{video.youtube_Id }}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
        <div class="card-body"><p class="card-text">{{video.title}}</p></div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

halls/templates/halls/delete_hall.html
{% extends "halls/base.html" %} {%block content%}
<div class="container">
  <h2>Are u sure you want to delete this hall of fame?</h2>
  <form method="post">
    {{form.as_p}} {% csrf_token %}
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
  <br />
  <h2>
    <a href="{% url 'detail_hall' hall.id %}">{{hall.title}}</a>
  </h2>
</div>
{% endblock %}

halls/templates/halls/detail_hall.html
{% extends "halls/base.html" %} {% block content %}
<div class="container">
  <h1>{{hall.title}}</h1>
  <h3 class="text-muted">{{hall.user.username}}</h3>

  {% if user.id == hall.user.id %}
  <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger">Delete</a>
  <a href="{% url 'update_hall' hall.id %}" class="btn btn-primary">Edit</a>
  <a href="{% url 'add_video' hall.id %}" class="btn btn-primary">Add Video</a>
  {% endif %}
  <div class="row">
    {% for vid in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe
          width="100%"
          height="225"
          src="https://www.youtube.com/embed/{{vid.youtube_id }}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
        <div class="card-body">
          <p class="card-text">{{vid.title}}</p>
          {% if user.id == hall.user.id %}
          <a href="{% url 'delete_video' vid.id %}" class="btn btn-danger"
            >Delete Video</a
          >
          {% endif %}
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endblock %}
</div>

halls/templates/halls/home.html
{% extends 'halls/base.html' %} {% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1>What's your personal hall of Fame</h1>
    <p class="lead text-muted">
      You know what they are, They're your goto videos.YOu have a top 10 list
      and its time to share them to everyone else.CLick the button below to get
      started!!
    </p>
    <p>
      <a href="{% url 'create_hall' %}" class="btn btn-primary"
        >Create Your Hall Of Fame!</a
      >
    </p>
  </div>
</section>
<div class="container">
  <h1 class="text-center">Popular Hall Of Fames</h1>
  {% for hall in popular_halls %}

  <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
  <div class="row">
    {% for vid in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe
          width="100%"
          height="225"
          src="https://www.youtube.com/embed/{{vid.youtube_id }}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
        <div class="card-body"><p class="card-text">{{vid.title}}</p></div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}

  <h1 class="text-center">Recent Hall of Fames</h1>
  {% for hall in recent_halls %}

  <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
  <div class="row">
    {% for vid in hall.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe
          width="100%"
          height="225"
          src="https://www.youtube.com/embed/{{vid.youtube_id }}"
          frameborder="0"
          allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen
        ></iframe>
        <div class="card-body"><p class="card-text">{{vid.title}}</p></div>
      </div>
    </div>
    {% endfor %}
  </div>
  {% endfor %}
</div>
{% endblock %}

halls/templates/halls/update_hall.html
{% extends "halls/base.html" %} {%block content%}
<div class="container">
  <h2>Edit the hall of fame</h2>
  {% load crispy_forms_tags %}
  <form method="post">
    {{form|crispy}} {% csrf_token %}
    <button type="submit" class="btn btn-primary">Save</button>
  </form>
  <br />
  <a href="{% url 'delete_hall' hall.id %}" class="btn btn-danger"
    >Delete Hall Of Fame</a
  >
</div>
{% endblock %}